### ISSUE TITLE
Update nom to 4.0

### ISSUE THREAD

**Issue by adwhit** [adwhit/tokio-stomp#1]
When it is released, of course

**Comment by filmor** [comment]
I guess this one is done, an update to 5 could be the new plan ;)

**Comment by zuisong** [comment]
I have created a new PR to update to the latest version of `nom`.
https://github.com/adwhit/tokio-stomp/pull/15

**Comment by adwhit** [comment]
PR has been closed?

**Comment by adwhit** [comment]
Closed in #16
