### ISSUE TITLE
Passing a different host on login than the actual host I'm connecting to. 

### ISSUE THREAD

**Issue by phowat** [adwhit/tokio-stomp#7]
Hi there, 

I have a weird corner case in which I need do send a different hostname when authenticating to the stomp server than the actual one I'm connecting to. 

Something like this:  I have to pass "hostname.company.intranet:61613"  to client::connect() so it can actually reach the server but in the CONNECT message I need the host parameter to be "otherhostname.company.intranet" . 

I did a quick hack so I could continue my work but if there is use for that feature upstream I could clean it up and send a pull request . Would you be interested ?

**Comment by adwhit** [comment]
Hi, thanks for the head's up. I made this library for a specific use but I don't need it any more so not really maintaining it. So I guess not really interested in a PR. If I ever start working on it again I'll consider adding it as a feature. Interesting to know this crate is getting a bit of use though!

**Comment by adwhit** [comment]
This has actually been fixed! in release `v0.4.0`
